#!/bin/bash

. ./config

PG_DOCKER_IMAGE=$PG_DOCKER_IMAGE || 'postgres'

docker run $DOCKER_OPTS -e PGPASSWORD=$PG_PASS $PG_DOCKER_IMAGE pg_dump -U $PG_USER --dbname=$PG_DB --host $PG_HOST | \
    gzip -9 > "$SOURCE/"$(date +"%Y-%m-%d")"_pgsql_"$PG_DB".sql.gz"
